### ISSUE TITLE
Can someone add python support to hlab.app?

### ISSUE THREAD

**Issue by maggch97** [Cat-Computing-Universe/PyLab#5]
hlab.app is a user-friendly NFT, Code Metaverse, Scientific Computing website. It's easily to share my code with my npy, mother and father on hlab.app. On PyLab, I don't even know how to submit the code other than submitting PR. This is very very very unfriendly to beginners like me.

I think the most urgent work for PyLab now is to copy the hlab.app code, replace 'hlab' with 'PyLab' and add python support.

Another question, is PyLab considering merging with hlab.app, it is not necessary to maintain two code repos. If merge, I think hlab.app should give PyLab 50% equity.

**Comment by bboczeng** [comment]
no, but you can help this repo build code snippet and user login. @maggch97 ?
